networks:
  proxy:
    external: true
    name: proxy

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER: "on"
      # these must be the public HTTPS hostnames you’ll put in NPM
      MINIO_SERVER_URL: https://${MINIO_S3_HOST}
      MINIO_BROWSER_REDIRECT_URL: https://${MINIO_CONSOLE_HOST}
    volumes:
      - /mnt/minio:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks: [proxy]
